_BASE_: "../Base-RCNN-FPN.yaml"
DATASETS:
  TRAIN: ("newspaper_train",)
  TEST: ("newspaper_test",)
DATALOADER:
  NUM_WORKERS: 4
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 1024
    NUM_CLASSES: 7
  RESNETS:
    DEPTH: 101

SOLVER:
  STEPS: []
  MAX_ITER: 255000
  IMS_PER_BATCH: 4
  BASE_LR: 0.0003

OUTPUT_DIR: "./output_mask_rcnn_R_101_FPN_3x"
